// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// read_PLY
List read_PLY(std::string input, std::string output);
RcppExport SEXP SomaMS_read_PLY(SEXP inputSEXP, SEXP outputSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type input(inputSEXP);
    Rcpp::traits::input_parameter< std::string >::type output(outputSEXP);
    __result = Rcpp::wrap(read_PLY(input, output));
    return __result;
END_RCPP
}
// poly_volume
double poly_volume(NumericMatrix x);
RcppExport SEXP SomaMS_poly_volume(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    __result = Rcpp::wrap(poly_volume(x));
    return __result;
END_RCPP
}
