# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_PLY <- function(input, output) {
    .Call('SomaMS_read_PLY', PACKAGE = 'SomaMS', input, output)
}

poly_volume <- function(x) {
    .Call('SomaMS_poly_volume', PACKAGE = 'SomaMS', x)
}

